### ISSUE TITLE
New submodule in Leads + Integration with calendar

### ISSUE THREAD

**Issue by laravelbap** [laravelbap/multicrm#14]
**1. Add next steps module inside leads and contacts.**
Title
Status
Date
Description

**2. Integrate calendar events with lead.** 

Possibility to add leads , contacts in event. Display list of events connected events in leads and contacts.

**Comment by horizontechbiz** [comment]
item 1 is basic need of any crm. Everytime i make a contact with a customer, i want to note down the next action, and when to take it in the future..either call him after 20 days or email him a followup in 3 days etc. Please add this feature ASAP

**Comment by horizontechbiz** [comment]
Any update on when we can expect this to be done?

**Comment by laravelbap** [comment]
Hi,
This is already added. In leads, contacts you can add events from calendar. or connect leads, contact to event in calendar view.
