### ISSUE TITLE
all installiation done but error with css files

### ISSUE THREAD

**Issue by ahtsham12-maker** [laravelbap/multicrm#19]
hey I
![12](https://user-images.githubusercontent.com/67753366/95727676-ee241500-0c93-11eb-9866-fad45f3e5312.PNG)
 install the bap through steps all done. bun now the site is not fetching the css data, the view is messy

**Comment by laravelbap** [comment]
Please send support request using https://laravel-bap.com/support-ticket/

**Comment by tmccanns** [comment]
So it would be nice if you posted the resolution for this issue. I am having the exact same issue!
