### ISSUE TITLE
installation error

### ISSUE THREAD

**Issue by developr007** [laravelbap/multicrm#2]
design@design-PC MINGW64 /c/wamp64/www/laravel_bap_crm
$ php artisan bap:install
Migration table created successfully.

In Connection.php line 664:

  SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was t
  oo long; max key length is 1000 bytes (SQL: alter table `comments` add inde
  x `comments_commentable_id_commentable_type_index`(`commentable_id`, `comme
  ntable_type`))

In PDOStatement.php line 144:

  SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was t
  oo long; max key length is 1000 bytes

In PDOStatement.php line 142:

  SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was t
  oo long; max key length is 1000 bytes

**Comment by laravelbap** [comment]
Hi,
update /config/database.php and set mysql settings

```
 'mysql' => [
            'charset' => 'utf8',
            'collation' => 'utf8_unicode_ci',
            'prefix' => '',
            'strict' => true,
            'engine' => 'InnoDB',
        ],
```

then run 
```
php artisan config:cache
php artisan bap:install // if you will have info that bap is already installed , run bellow command
php artisan migrate:fresh && php artisan bap:reseed

```
