### ISSUE TITLE
Make 'AutoDictWidget' clickable and filter the datatable

### ISSUE THREAD

**Issue by jenellej** [laravelbap/multicrm#7]
Hi,

Please make the autodictwidgets clickable to filter the table according to status.

If you can send instructions on how to do this to implement ahead of next release it will be much appreciated.

Thanks!

**Comment by laravelbap** [comment]
Done. Will be added to new release
If you will be doing new autodictwidgets here are changes that you will need to add.

New property "dataTableToFilter" id of datatable in current module.
```
<div class="row">
    @widget('Modules\Platform\Core\Widgets\AutoGroupDictWidget',
    [
    'coll_class' => 'col-lg-2 col-md-2 col-sm-6 col-xs-6',
    'dict' =>'Modules\Orders\Entities\OrderStatus',
    'moduleEntity' => 'Modules\Orders\Entities\Order',
    'moduleTable' =>'orders',
    'groupBy' => 'order_status_id',
    'dataTableToFilter' => 'dataTableBuilder'
    ]
    )
</div>

```

Example OrderDatatable->availableColumns 

new property  'column_name' => 'order_status_id'
```
'status' => [
                'name' => 'orders_dict_status.name',
                'data' => 'status',
                'title' => trans('orders::orders.form.status'),
                'data_type' => 'text',
                'filter_type' => 'text',
                'column_name' => 'order_status_id'
            ],
```
